baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'miguehm'
theme = 'LoveIt'

[params]
	title = "miguehm"

	[params.header]
		# desktop header mode ["fixed", "normal", "auto"]
		# 桌面端导航栏模式 ["fixed", "normal", "auto"]
		desktopMode = "fixed"
		# mobile header mode ["fixed", "normal", "auto"]
		# 移动端导航栏模式 ["fixed", "normal", "auto"]
		mobileMode = "auto"
		# Header title config
		# 页面头部导航栏标题配置
		[params.header.title]
		  # URL of the LOGO
		  # LOGO 的 URL
		  logo = ""
		  # title name
		  # 标题名称
		  name = "miguehm"
	
	[params.home]
		# amount of RSS pages
		# RSS 文章数目
		rss = 10
		# Home page profile
		# 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # URL of avatar shown in home page
      # 主页显示头像的 URL
      avatarURL = "/images/avatar.png"
      # title shown in home page (HTML format is supported)
      # 主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # subtitle shown in home page (HTML format is supported)
      # 主页显示的网站副标题 (允许 HTML 格式)
      subtitle = "Welcome to my world"
      # whether to use typeit animation for subtitle
      # 是否为副标题显示打字机动画
      typeit = true
      # whether to show social links
      # 是否显示社交账号
      social = true
      # disclaimer (HTML format is supported)
      # 免责声明 (支持 HTML 格式)
      disclaimer = ""
    # Home page posts
    # 主页文章列表
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      # 主页每页显示文章数量
      paginate = 6

	# Search config
	  # 搜索配置
	[params.search]
		enable = true
		# type of search engine ["lunr", "algolia"]
		# 搜索引擎的类型 ["lunr", "algolia"]
		type = "algolia"
		# max index length of the chunked content
		# 文章内容最长索引长度
		contentLength = 4000
		# placeholder of the search bar
		# 搜索框的占位提示语
		placeholder = ""
		# max number of results length
		# 最大结果数目
		maxResultLength = 10
		# snippet length of the result
		# 结果内容片段长度
		snippetLength = 30
		# HTML tag name of the highlight part in results
		# 搜索结果中高亮部分的 HTML 标签
		highlightTag = "em"
		# whether to use the absolute URL based on the baseURL in search index
		# 是否在搜索索引中使用基于 baseURL 的绝对路径
		absoluteURL = false

		[params.search.algolia]
		  index = "/"
		  appID = ""
		  searchKey = ""

	[params.social]
		GitHub = "miguehm"
		Instagram = "_miguehm"
		Email = "miguel.hernandezmor@alumno.buap.mx"
		Linkedin = "miguel-angel-h"
[menu]
    [[menu.main]]
		weight = 1
		identifier = "projects"
		# you can add extra information before the name (HTML format is supported), such as icons
		# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
		pre = ""
		# you can add extra information after the name (HTML format is supported), such as icons
		# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
		post = ""
		name = "Proyectos"
		url = "/projects/"
		# title will be shown when you hover on this menu link
		# 当您将鼠标悬停在此菜单链接上时, 将显示标题
		title = ""

	[[menu.main]]
		weight = 2
		identifier = "tutorials"
		pre = ""
		post = ""
		name = "Fotografía"
		url = "/tutorials/"
		title = "Some useful tutorials"
